---
# This role contains common plays that will run on all nodes.

- name: Install haproxy
  yum: name={{ item }} state=present
  with_items:
   - haproxy

- name: Copy iptables configuration
  copy:
    src: ../files/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: 0640

- name: Creates directory
  file:
    path: /var/lib/haproxy
    state: directory
    owner: haproxy
    group: haproxy

- name: Start service haproxy, if not running
  service:
    name: haproxy
    enabled: yes
    state: started
